### ISSUE TITLE
KeyError: 'content-length' when behind a proxy (it seems like!)

### ISSUE THREAD

**Issue by parkouss** [armenzg/mozilla_ci_tools#210]
I am using the trigger_job function. Everything goes fine when I do that at home (without proxy), but trying to use that at work (where there is a proxy), I got the following error:
```
INFO:mozci:We want to trigger 'Ubuntu VM 12.04 x64 fx-team debug test mochitest-browser-chrome-1' on revision '77dd978b8ef3' a total of 20 time(s).
Traceback (most recent call last):
  File "/home/jp/dev/mozbattue/venv/bin/mozbattue", line 9, in <module>
    load_entry_point('mozbattue==0.1', 'console_scripts', 'mozbattue')()
  File "/home/jp/dev/mozbattue/mozbattue/main.py", line 251, in main
    opts.func(opts)
  File "/home/jp/dev/mozbattue/mozbattue/main.py", line 119, in do_trigger
    times=opts.times, dry_run=opts.dry_run)
  File "/home/jp/dev/mozbattue/mozbattue/trigger.py", line 37, in trigger_jobs
    trigger_job(revision, buildername, times=times, dry_run=dry_run)
  File "/home/jp/dev/mozbattue/venv/local/lib/python2.7/site-packages/mozci/mozci.py", line 344, in trigger_job
    buildername,
  File "/home/jp/dev/mozbattue/venv/local/lib/python2.7/site-packages/mozci/mozci.py", line 121, in _determine_trigger_objective
    status = buildapi.query_job_status(job)
  File "/home/jp/dev/mozbattue/venv/local/lib/python2.7/site-packages/mozci/sources/buildapi.py", line 153, in query_job_status
    req["request_id"])
  File "/home/jp/dev/mozbattue/venv/local/lib/python2.7/site-packages/mozci/sources/buildjson.py", line 158, in query_job_data
    jobs = _fetch_data(filename)
  File "/home/jp/dev/mozbattue/venv/local/lib/python2.7/site-packages/mozci/sources/buildjson.py", line 42, in _fetch_data
    json_contents = load_file(filepath, url)
  File "/home/jp/dev/mozbattue/venv/local/lib/python2.7/site-packages/mozci/utils/transfer.py", line 148, in load_file
    return _fetch_and_load_file(req, filepath)
  File "/home/jp/dev/mozbattue/venv/local/lib/python2.7/site-packages/mozci/utils/transfer.py", line 37, in _fetch_and_load_file
    size = int(req.headers['Content-Length'].strip())
  File "/home/jp/dev/mozbattue/venv/local/lib/python2.7/site-packages/requests/structures.py", line 54, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'content-length'
```
Seems like 'content-length' is missing from the requests headers when the proxy is used.

I printed the url and the req.headers just before the crash (more precisely https://github.com/armenzg/mozilla_ci_tools/blob/cee46f52354b9918210d2b5821fbc07cd79b3be4/mozci/utils/transfer.py#L146):
```
http://builddata.pub.build.mozilla.org/builddata/buildjson/builds-2015-05-08.js.gz
{'via': '1.1 INTERNET1', 'proxy-connection': 'Keep-Alive', 'transfer-encoding': 'chunked', 'x-backend-server': 'web1.releng.webapp.scl3.mozilla.com', 'accept-ranges': 'bytes', 'expires': 'Tue, 19 May 2015 10:21:46 GMT', 'server': 'Apache', 'last-modified': 'Sat, 09 May 2015 02:03:16 GMT', 'connection': 'Keep-Alive', 'etag': '"1368482"', 'cache-control': 'max-age=60', 'date': 'Tue, 19 May 2015 10:20:46 GMT', 'access-control-allow-origin': '*', 'content-type': 'text/plain; charset=UTF-8'}
```

Note that I know that the network behind that proxy is bad, and I wouldn't be surprised if the original bug comes from the proxy itself. :) Just reporting this so you can take action if you want to.

**Comment by vaibhavmagarwal** [comment]
I think that since there is no possible way to know beforehand the size of the response if 'Content-Length' header is not present, we should have default value for 'size' variable in https://github.com/armenzg/mozilla_ci_tools/blob/master/mozci/utils/transfer.py#L37

We use that variable to download requests and if we keep it above the maximum size for download, it will download the whole response, with just a bit of inaccuracy in the UI for progressbar, which should be ok.

**Comment by vaibhavmagarwal** [comment]
Working on this.

**Comment by vaibhavmagarwal** [comment]
Thanks Julien for the patch! I am closing this now since this should be fixed, reopen if similar problem arises.

**Comment by parkouss** [comment]
Hello guys, I still have the issue since my patch was backed out. :) But I can't reopen it... (http://stackoverflow.com/questions/21333654/how-to-re-open-an-issue-in-github).
Could you reopen this issue please ? And if I can be of any help here, please tell me. Maybe I can rework on this if I can understand what did not worked in the first patch.

Thanks!

**Comment by armenzg** [comment]
Hey @parkouss if you could give it a try that would be great.
I think just testing it from home might be sufficient.

I'm kicking myself for not having more information about why we backed it out.

**Comment by parkouss** [comment]
Hey @armenzg, no need to kick yourself for that!
I'll be able to test this tomorrow (the bug appears at my work office).

**Comment by armenzg** [comment]
Hi @parkouss I'm going to close this for now.
Please let us know if you come back to this and you still hit this issue.
