### ISSUE TITLE
KeyError: 'triggered_by'

### ISSUE THREAD

**Issue by vaibhavmagarwal** [armenzg/mozilla_ci_tools#27]
(venv)vaibhav@vaibhav:~/mozilla_ci_tools/scripts$ python trigger_range.py --rev=88c746188a40 --buildername='Rev5 MacOSX Mountain Lion 10.8 mozilla-inbound talos svgr' --repo-name=mozilla-inbound --times=6 --debug --delta=6 --dry-run
Traceback (most recent call last):
  File "trigger_range.py", line 4, in <module>
    from mozci.mozci import trigger_range, query_repo_url
  File "/home/vaibhav/mozilla_ci_tools/mozci/mozci.py", line 14, in <module>
    from mozci.platforms import associated_build_job, does_builder_need_files
  File "/home/vaibhav/mozilla_ci_tools/mozci/platforms.py", line 37, in <module>
    buildername_to_trigger[builder] = values['triggered_by'][0]
KeyError: 'triggered_by'

This is a new error I am facing.

**Comment by adusca** [comment]
triggered_by is a new key added this week in allthethings.json
If you remove allthethings.json and run the script again it should work, but the real problem is that alllthethings.py only checks if a file named allthethings.json already exists, and if it does it returns that without downloading anything. That makes sense to avoid downloading the same file several times in a row, but it can cause us to use old info. Maybe we should check if the file is less than a day old and download again if it's not?

**Comment by vaibhavmagarwal** [comment]
Yes, I think we should check if we have a old file (based on date) and download if a new one is available. That should be a good way to go about it.

**Comment by armenzg** [comment]
I also want to land this code:
https://pastebin.mozilla.org/8822617

Does  this work for you?

**Comment by armenzg** [comment]
If any of you file an issue, also mention if you're working on it so I don't start touching it.
I'm grabbing this for now.

**Comment by vaibhavmagarwal** [comment]
@armenzg: after doing your changes, now it is working for me. Also, as @adusca mentioned, changes required to download new version of files will be required in https://github.com/armenzg/mozilla_ci_tools/blob/master/mozci/sources/allthethings.py#L18

**Comment by armenzg** [comment]
Fixed in "master":
https://github.com/armenzg/mozilla_ci_tools/commit/798ddcdd77b43f917a5b79fd87dd4f6ab67a9bd2

Please re-open if you still hit the issue.

**Comment by vaibhavmagarwal** [comment]
This issue still occurs on my another machine:

Traceback (most recent call last):
  File "trigger_range.py", line 4, in <module>
    from mozci.mozci import trigger_range, query_repo_url
  File "/home/vaibhav/mozilla_ci_tools/mozci/mozci.py", line 14, in <module>
    from mozci.platforms import associated_build_job, does_builder_need_files
  File "/home/vaibhav/mozilla_ci_tools/mozci/platforms.py", line 37, in <module>
    buildername_to_trigger[builder] = values['triggered_by'][0]
KeyError: 'triggered_by'

**Comment by armenzg** [comment]
This has been fixed with my latest commit. Thanks also for the pull request.
