### ISSUE TITLE
mozci is busted on Windows

### ISSUE THREAD

**Issue by rvandermeulen** [armenzg/mozilla_ci_tools#299]
$ mozci-trigger -b "Android armv7 API 9 mozilla-central debug build" -r e7434cafdf2f
07/22/2015 10:57:20 INFO:        We want to have 1 job(s) of Android armv7 API 9 mozilla-central deb
ug build on revisions ['e7434cafdf2f']
07/22/2015 10:57:20 INFO:
07/22/2015 10:57:20 INFO:        === e7434cafdf2f ===
07/22/2015 10:57:21 INFO:        We want to have 1 job(s) of Android armv7 API 9 mozilla-central deb
ug build on revision e7434cafdf2f
builds-4hr.js: [>>>>>>>>>>>>>>>>>>>>>>] Elapsed Time: 0:00:01   2.72 MB/s 3.0MB

gzip: c:/Users/Ryan/.mozilla/mozci/builds-4hr.js: invalid compressed data--format violated
07/22/2015 10:57:23 ERROR:       'CalledProcessError' object has no attribute 'errno'
Traceback (most recent call last):
  File "c:\mozilla-build\python\lib\site-packages\mozci\scripts\trigger.py", line 251, in main
    trigger_build_if_missing=options.trigger_build_if_missing
  File "c:\mozilla-build\python\lib\site-packages\mozci\mozci.py", line 387, in trigger_range
    successful_jobs, pending_jobs, running_jobs = _status_summary(matching_jobs)[0:3]
  File "c:\mozilla-build\python\lib\site-packages\mozci\mozci.py", line 69, in _status_summary
    status = QUERY_SOURCE.get_job_status(job)
  File "c:\mozilla-build\python\lib\site-packages\mozci\query_jobs.py", line 92, in get_job_status
    return self._is_coalesced(job)
  File "c:\mozilla-build\python\lib\site-packages\mozci\query_jobs.py", line 104, in _is_coalesced
    status_data = query_job_data(req["complete_at"], req["request_id"])
  File "c:\mozilla-build\python\lib\site-packages\mozci\sources\buildjson.py", line 147, in query_jo
b_data
    job = _find_job(request_id, _fetch_data(filename), filename)
  File "c:\mozilla-build\python\lib\site-packages\mozci\sources\buildjson.py", line 45, in _fetch_da
ta
    json_contents = load_file(filepath, url)
  File "c:\mozilla-build\python\lib\site-packages\mozci\utils\transfer.py", line 189, in load_file
    return _load_json_file(filepath)
  File "c:\mozilla-build\python\lib\site-packages\mozci\utils\transfer.py", line 95, in _load_json_f
ile
    if e.errno == errno.ENOENT:
AttributeError: 'CalledProcessError' object has no attribute 'errno'

**Comment by vaibhavmagarwal** [comment]
This error happens here: https://github.com/armenzg/mozilla_ci_tools/blob/85eb5e992673927a267b95953f9de889690cf80c/mozci/utils/transfer.py#L103

**Comment by adusca** [comment]
Fixed in #300, but not released yet.

**Comment by adusca** [comment]
The fix was released in mozci 0.12.0.

**Comment by rvandermeulen** [comment]
Still broken for me. pip says my mozci install is current.

$ mozci-triggerbyfilters -i "10.10,crashtest" try c2ae67ce82dc
2 jobs will be triggered, do you wish to continue? y/n/d (d=show details) d
08/01/2015 04:22:05 INFO:        The following jobs will be triggered:
 Rev5 MacOSX Yosemite 10.10 try debug test crashtest
Rev5 MacOSX Yosemite 10.10 try opt test crashtest
Do you wish to continue? y/n y
08/01/2015 04:22:09 INFO:        We want to have 1 job(s) of Rev5 MacOSX Yosemite 10.10 try debug te
st crashtest on revisions ['c2ae67ce82dc']
08/01/2015 04:22:09 INFO:
08/01/2015 04:22:09 INFO:        === c2ae67ce82dc ===
08/01/2015 04:22:09 INFO:        We want to have 1 job(s) of Rev5 MacOSX Yosemite 10.10 try debug te
st crashtest on revision c2ae67ce82dc
08/01/2015 04:22:10 INFO:        We have found 0 potential job(s) matching 'Rev5 MacOSX Yosemite 10.
10 try debug test crashtest' on c2ae67ce82dc. We need to trigger more.
08/01/2015 04:22:10 INFO:        ===> We want to trigger 'Rev5 MacOSX Yosemite 10.10 try debug test
crashtest' on revision 'c2ae67ce82dc' a total of 1 time(s).
08/01/2015 04:22:10 INFO:
08/01/2015 04:22:10 INFO:        The local file was last modified in Wed, 22 Jul 2015 15:00:40 GMT.
08/01/2015 04:22:10 INFO:        The server's last modified in Sat, 01 Aug 2015 20:22:05 GMT
08/01/2015 04:22:10 INFO:        We need to fetch it again.
builds-4hr.js: [>>>>>>>>>>>>>>>>>>>>>>] Elapsed Time: 0:00:00 581.21 kB/s 0.0MB
08/01/2015 04:22:12 INFO:        We have the necessary files to trigger the downstream job.
Traceback (most recent call last):
  File "c:\mozilla-build\python\Scripts\mozci-triggerbyfilters-script.py", line 9, in <module>
    load_entry_point('mozci==0.12.0', 'console_scripts', 'mozci-triggerbyfilters')()
  File "c:\mozilla-build\python\lib\site-packages\mozci\scripts\triggerbyfilters.py", line 107, in m
ain
    dry_run=options.dry_run,
  File "c:\mozilla-build\python\lib\site-packages\mozci\mozci.py", line 424, in trigger_range
    trigger_build_if_missing=trigger_build_if_missing)
  File "c:\mozilla-build\python\lib\site-packages\mozci\mozci.py", line 364, in trigger_job
    clean_directory()
  File "c:\mozilla-build\python\lib\site-packages\mozci\utils\transfer.py", line 43, in clean_direct
ory
    permissible_timestamp = int(permissible_last_date.strftime("%s"))
ValueError: Invalid format string

**Comment by vaibhavmagarwal** [comment]
This issue should be fixed in the latest 0.13.0 release, so closing this. Ryan, if you still face problems, comment on this issue.
